# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hospital_no',
            field=models.PositiveIntegerField(default=911),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_no',
            field=models.PositiveIntegerField(default=112),
        ),
    ]
